name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
      - run: pnpm install

      - name: Build
        run: cd docs && pnpm run docs:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.RTY_UI_PLUS_TOEKN }}
          publish_dir: docs/.vitepress/dist